version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    command: redis-server --appendonly yes
    networks:
      - redis_network

networks:
  redis_network:
    driver: bridge

volumes:
  redis_data:
    driver: local